name: "Pipeline"

on:
    push:
        branches:
            - "main"

jobs:
    trigger-workflow:
        runs-on: ubuntu-latest

        steps:

        - name: Echo WF Name
          shell: bash
          run: |
              echo "Activa WF Padre"

        -  name: Llamar WF Hijo
           uses: ccelisp/repo-hijo/.github/workflows/pipeline.yml@main

    build:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout repository
                uses: actions/checkout@v2

            -   name: Saludar
                run: |
                    echo "Hola Mundo"
