name: "Pipeline"

on:
    push:
        branches:
            - "main"

jobs:
    trigger-workflow:
        runs-on: ubuntu-latest

        steps:

        - name: Echo WF Name
          shell: bash
          run: |
              echo "Activa WF Padre"

        -  name: Llamar WF Hijo
           uses: convictional/trigger-workflow-and-wait@v.1.6.1
           with:
               owner: ccelisp
               repo: repo-hijo
               github_token: ${{ secrets.PERSONAL_TOKEN }}
               workflow_file_name: pipeline.yml
               ref: main
               wait_interval: 10
               propagate_failure: true
               trigger_workflow: true
               wait_workflow: true
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout repository
                uses: actions/checkout@v2

            -   name: Saludar
                run: |
                    echo "Hola Mundo"
