name: "Pipeline"

on:
    push:
        branches:
            - "main"

jobs:

    call-workflow-passing-data:
        uses: ccelisp/repo-hijo/.github/workflows/pipeline.yml@main
        secrets:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

    build:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout repository
                uses: actions/checkout@v2

            -   name: Saludar
                run: |
                    echo "Hola Mundo"
